version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - worldbank-network      
    depends_on:
      - "bff"    
  bff:
    image: bff
    build:
      context: ./bff
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    ports:
      - "8080:8080"      
    networks:
      - worldbank-network        
networks:
  worldbank-network:
    driver: bridge