version: '3'

services:
  tasks:
    image: quarkus-worldbanks/quartz:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    networks:
      - tasks-network
  nginx:
    image: nginx:1.17.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tasks
    ports:
      - 8080:8080
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge